baseURL = "https://imperialwicket.com/"
languageCode = "en-us"
title = "imperialWicket"
theme="archie"
copyright = ""
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# disqusShortname = "yourDisqusShortname"

ignoreLogs = ['warning-goldmark-raw-html']

[pagination]
	pagerSize=5 # articles per page

[params]
	mode="toggle" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "Technical musings from an opinionated Platform Engineer/Leader"
	mathjax = false # enable MathJax support
	katex = false # enable KaTeX support

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/imperialWicket"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/nw_iw/"

# Main menu Items

#[[menu.main]]
#name = "Home"
#url = "/"
#weight = 1

[[menu.main]]
name = "archives"
url = "/post"
weight = 2

[[menu.main]]
name = "about"
url = "/about"
weight = 3

[[menu.main]]
name = "tags"
url = "/tags"
weight = 4

ignoreLogs = ['warning-goldmark-raw-html']
